CREATE DATABASE electricity;

USE electricity;

CREATE TABLE IF NOT EXISTS Counter (
	id INT AUTO_INCREMENT PRIMARY KEY,
	client_id INT NOT NULL,
	e_value INT NOT NULL
);


CREATE TABLE IF NOT EXISTS Total (
	id INT AUTO_INCREMENT PRIMARY KEY,
	total INT NOT NULL
);
